set local check_function_bodies = off;

/**
 * The menu: `categories` and `dishes`.
 *
 * Everything for these two tables lives in this single file on purpose: DDL,
 * indexes, policies and grants. A table without its policies is a broken table
 * in this repo — the `ensure_rls` event trigger enables RLS on every new table
 * of `public`, so a policy-less table returns zero rows to everyone. Splitting
 * this migration in two would make that half-applied state reachable.
 *
 * Names are in English (docs/panel.md §2, note of 31/08/2026): `dishes`, not
 * `platos`; `price_cents`, not `precio_centimos`. They match
 * src/features/menu/types.ts column for column.
 */

create table "public"."categories" (
  "id"         bigint  generated by default as identity not null,
  "name"       text    not null,
  -- The menu is ordered by hand, not alphabetically.
  "sort_order" integer not null default 0,
  constraint "categories_pkey" primary key (id)
);

create table "public"."dishes" (
  "id"          bigint                   generated by default as identity not null,
  "name"        text                     not null,
  "description" text                     not null default ''::text,
  -- Cents as an integer, never a float: 18.50 has no exact binary
  -- representation and you end up with dishes priced at 18.499999. The
  -- formatting to "18,50 €" happens in the client (menu/formatPrice.ts).
  "price_cents" integer                  not null,
  "category_id" bigint                   not null,
  -- Position inside its category.
  "sort_order"  integer                  not null default 0,
  -- Taking a dish off the menu does not delete it: it comes back in March with
  -- its description intact. See docs/panel.md §2.
  "available"   boolean                  not null default true,
  -- Path in Storage, not a full URL: if the project domain changes, stored
  -- URLs break and paths do not. Unused until phase 5.
  "photo_path"  text,
  "created_at"  timestamp with time zone not null default now(),
  "updated_at"  timestamp with time zone not null default now(),
  constraint "dishes_pkey" primary key (id)
);

-- `on delete restrict`, not cascade: deleting a category that still has dishes
-- must fail loudly rather than silently take the dishes with it. The panel
-- translates the resulting Postgres error into a readable sentence.
alter table "public"."dishes"
  add constraint "dishes_category_id_fkey" foreign key (category_id)
  references public."categories"(id) on delete restrict;

-- Every foreign key that gets filtered on needs its own index; Postgres does
-- not create one for it. No index on `available`: with 60 dishes it earns
-- nothing.
create index dishes_category_id_idx on public."dishes" using btree (category_id);

/**
 * Keeps `updated_at` honest. Doing it in the client would mean trusting six
 * different call sites to remember.
 */
create or replace function private.touch_updated_at()
  returns trigger
  language plpgsql
  set search_path to ''
  AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

create trigger dishes_touch_updated_at
  before update on public."dishes"
  for each row
  execute function private.touch_updated_at();

alter table "public"."categories" enable row level security;
alter table "public"."dishes"     enable row level security;

-- The two-policy mould of docs/panel.md §3. Note `categories` reads with
-- `using (true)`: it has no `available` column, and copying the mould blindly
-- is the easy mistake here.
create policy "carta publica" on "public"."categories"
  for select to "anon", "authenticated"
  using (true);

create policy "admins escriben" on "public"."categories"
  for all to "authenticated"
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

-- Unavailable dishes never leave the database for the public menu. The panel
-- still sees them: policies are OR'ed, and "admins escriben" is `for all`,
-- so an admin's select matches it and returns every row.
create policy "carta publica" on "public"."dishes"
  for select to "anon", "authenticated"
  using (available);

create policy "admins escriben" on "public"."dishes"
  for all to "authenticated"
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

-- Explicit grants, same as was done with Admins. RLS already covers this, but
-- the first migration's `alter default privileges` handed write access on
-- future tables to `anon`, and one layer of defence is not defence in depth.
revoke all on table "public"."categories" from "anon", "authenticated";
revoke all on table "public"."dishes"     from "anon", "authenticated";

grant select on table "public"."categories" to "anon", "authenticated";
grant select on table "public"."dishes"     to "anon", "authenticated";

grant insert, update, delete on table "public"."categories" to "authenticated";
grant insert, update, delete on table "public"."dishes"     to "authenticated";

grant execute on function "private"."touch_updated_at"() to "postgres";


/**
 * Provisional seed data.
 *
 * ⚠️ (02/09/2026) These are the example dishes and prices that used to live in
 * src/features/menu/data/menu.json — whole roast chicken at 12,00 € is a
 * placeholder, not the real price. The real menu has to be asked for at the
 * asador; when it arrives, update the rows and take the "precios de ejemplo"
 * notice out of features/landing/components/MenuSection.
 *
 * It lives inside this migration rather than in supabase/seed.sql because
 * `supabase db push` applies migrations and not seeds, and a menu of empty
 * tables is not something anyone can look at. Every insert is guarded by
 * `not exists`, so re-running this file adds nothing twice. Ids are never
 * written by hand, so the identity sequence stays in step with the rows the
 * panel creates afterwards.
 */

insert into public."categories" (name, sort_order)
select v.name, v.sort_order
from (values
  ('Brasa',      1),
  ('Para picar', 2)
) as v(name, sort_order)
where not exists (
  select 1 from public."categories" c where c.name = v.name
);

insert into public."dishes" (name, description, price_cents, category_id, sort_order, available)
select
  v.name,
  v.description,
  v.price_cents,
  (select c.id from public."categories" c where c.name = v.category),
  v.sort_order,
  v.available
from (values
  ('Pollo asado entero',      'Criado en corral, hecho despacio a la brasa de encina.', 1200, 'Brasa',      1, true),
  ('Medio pollo asado',       '',                                                        650, 'Brasa',      2, true),
  ('Costillas a la brasa',    'Costilla de cerdo marinada 24 horas.',                   1400, 'Brasa',      3, true),
  ('Patatas fritas caseras',  '',                                                        350, 'Para picar', 1, true),
  ('Croquetas caseras (6 u.)','De jamón, hechas cada mañana.',                           600, 'Para picar', 2, true),
  -- Deliberately off the menu: it is what proves the RLS filter works when the
  -- public page does not show it. Do not make it available.
  ('Pimientos del piquillo',  'Fuera de carta hasta la próxima temporada.',              500, 'Para picar', 3, false)
) as v(name, description, price_cents, category, sort_order, available)
where not exists (
  select 1 from public."dishes" d where d.name = v.name
);
